/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncc.kiran.laptop_store_managent.views;

import edu.ncc.kiran.laptop_store_managent.controllers.Database;
import edu.ncc.kiran.laptop_store_managent.models.UserInfo;

/**
 *
 * @author kiran
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    UserInfo loggedInUserInfo;
    Database db = new Database();

    public AdminDashboard(UserInfo loggedInUserInfo) {
        initComponents();
        setLocationRelativeTo(null);
        db.GetDbConnection();
        // conn = Database.conn;
        this.loggedInUserInfo = loggedInUserInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdd = new javax.swing.JMenu();
        jMenuItemUser = new javax.swing.JMenuItem();
        jMenuItemLaptopBrand = new javax.swing.JMenuItem();
        jMenuItemLaptop = new javax.swing.JMenuItem();
        jMenuItemCustomer = new javax.swing.JMenuItem();
        jMenuItemCustomerTransaction = new javax.swing.JMenuItem();
        jMenuItemSupplier = new javax.swing.JMenuItem();
        jMenuItemOrder = new javax.swing.JMenuItem();
        jMenuUpdateDeleteSearch = new javax.swing.JMenu();
        jMenuItemCustomerViewUpdate = new javax.swing.JMenuItem();
        jMenuItemCustomerTransViewUpdate = new javax.swing.JMenuItem();
        jMenuItemSupplierOrder = new javax.swing.JMenuItem();
        jMenuItemSupplierTransaction = new javax.swing.JMenuItem();
        jMenuItemUser2 = new javax.swing.JMenuItem();
        jMenuItemSupplierView = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        jMenuAdd.setText("Add");

        jMenuItemUser.setText("User");
        jMenuItemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemUser);

        jMenuItemLaptopBrand.setText("Laptop brand");
        jMenuItemLaptopBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaptopBrandActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemLaptopBrand);

        jMenuItemLaptop.setText("Laptop");
        jMenuItemLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaptopActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemLaptop);

        jMenuItemCustomer.setText("Customer");
        jMenuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemCustomer);

        jMenuItemCustomerTransaction.setText("Customer Transaction");
        jMenuItemCustomerTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerTransactionActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemCustomerTransaction);

        jMenuItemSupplier.setText("Supplier");
        jMenuItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemSupplier);

        jMenuItemOrder.setText("Order");
        jMenuItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderActionPerformed(evt);
            }
        });
        jMenuAdd.add(jMenuItemOrder);

        jMenuBar1.add(jMenuAdd);

        jMenuUpdateDeleteSearch.setText("Update / Delete / View");

        jMenuItemCustomerViewUpdate.setText("Customer");
        jMenuItemCustomerViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerViewUpdateActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemCustomerViewUpdate);

        jMenuItemCustomerTransViewUpdate.setText("Customer Transaction");
        jMenuItemCustomerTransViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerTransViewUpdateActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemCustomerTransViewUpdate);

        jMenuItemSupplierOrder.setText("Order");
        jMenuItemSupplierOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierOrderActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemSupplierOrder);

        jMenuItemSupplierTransaction.setText("Supplier Transaction");
        jMenuItemSupplierTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierTransactionActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemSupplierTransaction);

        jMenuItemUser2.setText("User");
        jMenuItemUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUser2ActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemUser2);

        jMenuItemSupplierView.setText("Supplier");
        jMenuItemSupplierView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSupplierViewActionPerformed(evt);
            }
        });
        jMenuUpdateDeleteSearch.add(jMenuItemSupplierView);

        jMenuBar1.add(jMenuUpdateDeleteSearch);

        logoutMenu.setBackground(new java.awt.Color(255, 102, 102));
        logoutMenu.setForeground(new java.awt.Color(255, 51, 51));
        logoutMenu.setText("Log out");
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserActionPerformed

        final AddNewUser objaddAddNewUser = new AddNewUser(new javax.swing.JFrame(), true);
        objaddAddNewUser.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objaddAddNewUser.dispose();
            }
        });
        objaddAddNewUser.setLocationRelativeTo(this);
        objaddAddNewUser.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemUserActionPerformed

    private void jMenuItemLaptopBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaptopBrandActionPerformed
        // TODO add your handling code here:
        final AddNewLaptopBrand objaddAddNewLaptopBrand = new AddNewLaptopBrand(new javax.swing.JFrame(), true, loggedInUserInfo);
        objaddAddNewLaptopBrand.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objaddAddNewLaptopBrand.dispose();
            }
        });
        objaddAddNewLaptopBrand.setLocationRelativeTo(this);
        objaddAddNewLaptopBrand.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemLaptopBrandActionPerformed

    private void jMenuItemLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaptopActionPerformed
        // TODO add your handling code here:
        final AddNewLaptop objaddAddNewLaptop = new AddNewLaptop(new javax.swing.JFrame(), true, loggedInUserInfo);
        objaddAddNewLaptop.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objaddAddNewLaptop.dispose();
            }
        });
        objaddAddNewLaptop.setLocationRelativeTo(this);
        objaddAddNewLaptop.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemLaptopActionPerformed

    private void jMenuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerActionPerformed
        // TODO add your handling code here:
        final AddNewCustomer objaddAddNewCustomer = new AddNewCustomer(new javax.swing.JFrame(), true, loggedInUserInfo);
        objaddAddNewCustomer.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objaddAddNewCustomer.dispose();
            }
        });
        objaddAddNewCustomer.setLocationRelativeTo(this);
        objaddAddNewCustomer.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemCustomerActionPerformed

    private void jMenuItemCustomerTransViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerTransViewUpdateActionPerformed
        // TODO add your handling code here:
        final ViewAllCustomerTransaction objViewAllCustomerTransaction = new ViewAllCustomerTransaction(new javax.swing.JFrame(), true, loggedInUserInfo);
        objViewAllCustomerTransaction.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllCustomerTransaction.dispose();
            }
        });
        objViewAllCustomerTransaction.setLocationRelativeTo(this);
        objViewAllCustomerTransaction.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemCustomerTransViewUpdateActionPerformed

    private void jMenuItemCustomerViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerViewUpdateActionPerformed
        // TODO add your handling code here:
        final ViewAllCustomer objViewAllCustomer = new ViewAllCustomer(new javax.swing.JFrame(), true);
        objViewAllCustomer.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllCustomer.dispose();
            }
        });
        objViewAllCustomer.setLocationRelativeTo(this);
        objViewAllCustomer.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemCustomerViewUpdateActionPerformed

    private void jMenuItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierActionPerformed
        // TODO add your handling code here:
        final AddNewSupplier objAddNewSupplier = new AddNewSupplier(new javax.swing.JFrame(), true);
        objAddNewSupplier.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objAddNewSupplier.dispose();
            }
        });
        objAddNewSupplier.setLocationRelativeTo(this);
        objAddNewSupplier.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemSupplierActionPerformed

    private void jMenuItemOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrderActionPerformed
        // TODO add your handling code here:
        final AddNewOrder objAddNewOrder = new AddNewOrder(new javax.swing.JFrame(), true);
        objAddNewOrder.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objAddNewOrder.dispose();
            }
        });
        objAddNewOrder.setLocationRelativeTo(this);
        objAddNewOrder.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemOrderActionPerformed

    private void jMenuItemSupplierOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierOrderActionPerformed
        // TODO add your handling code here:
        final ViewAllOrder objViewAllOrder = new ViewAllOrder(new javax.swing.JFrame(), true);
        objViewAllOrder.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllOrder.dispose();
            }
        });
        objViewAllOrder.setLocationRelativeTo(this);
        objViewAllOrder.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemSupplierOrderActionPerformed

    private void jMenuItemSupplierTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierTransactionActionPerformed
        // TODO add your handling code here:
        final ViewAllSupplierTransaction objViewAllSupplierTransaction = new ViewAllSupplierTransaction(new javax.swing.JFrame(), true);
        objViewAllSupplierTransaction.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllSupplierTransaction.dispose();
            }
        });
        objViewAllSupplierTransaction.setLocationRelativeTo(this);
        objViewAllSupplierTransaction.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemSupplierTransactionActionPerformed

    private void jMenuItemUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUser2ActionPerformed
        // TODO add your handling code here:
        final ViewAllUser objViewAllUser = new ViewAllUser(new javax.swing.JFrame(), true);
        objViewAllUser.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllUser.dispose();
            }
        });
        objViewAllUser.setLocationRelativeTo(this);
        objViewAllUser.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemUser2ActionPerformed

    private void jMenuItemSupplierViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSupplierViewActionPerformed
        // TODO add your handling code here:
        final ViewAllSupplier objViewAllSupplier = new ViewAllSupplier(new javax.swing.JFrame(), true);
        objViewAllSupplier.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objViewAllSupplier.dispose();
            }
        });
        objViewAllSupplier.setLocationRelativeTo(this);
        objViewAllSupplier.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemSupplierViewActionPerformed

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        // TODO add your handling code here:
        this.dispose();
        UserLoginFrom ul = new UserLoginFrom();
        ul.setVisible(true);
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void jMenuItemCustomerTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerTransactionActionPerformed
        // TODO add your handling code here:
        final AddNewCustomerTransaction objAddNewCustomerTransaction = new AddNewCustomerTransaction(new javax.swing.JFrame(), true, loggedInUserInfo);
        objAddNewCustomerTransaction.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                objAddNewCustomerTransaction.dispose();
            }
        });
        objAddNewCustomerTransaction.setLocationRelativeTo(this);
        objAddNewCustomerTransaction.setVisible(true);
        this.validate();
    }//GEN-LAST:event_jMenuItemCustomerTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuAdd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCustomer;
    private javax.swing.JMenuItem jMenuItemCustomerTransViewUpdate;
    private javax.swing.JMenuItem jMenuItemCustomerTransaction;
    private javax.swing.JMenuItem jMenuItemCustomerViewUpdate;
    private javax.swing.JMenuItem jMenuItemLaptop;
    private javax.swing.JMenuItem jMenuItemLaptopBrand;
    private javax.swing.JMenuItem jMenuItemOrder;
    private javax.swing.JMenuItem jMenuItemSupplier;
    private javax.swing.JMenuItem jMenuItemSupplierOrder;
    private javax.swing.JMenuItem jMenuItemSupplierTransaction;
    private javax.swing.JMenuItem jMenuItemSupplierView;
    private javax.swing.JMenuItem jMenuItemUser;
    private javax.swing.JMenuItem jMenuItemUser2;
    private javax.swing.JMenu jMenuUpdateDeleteSearch;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu logoutMenu;
    // End of variables declaration//GEN-END:variables
}
