/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncc.kiran.laptop_store_managent.views;

import edu.ncc.kiran.laptop_store_managent.controllers.Database;
import edu.ncc.kiran.laptop_store_managent.controllers.LaptopBrandManagement;
import edu.ncc.kiran.laptop_store_managent.controllers.LaptopManagment;
import edu.ncc.kiran.laptop_store_managent.models.LaptopBrandInfo;
import edu.ncc.kiran.laptop_store_managent.models.LaptopInfo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kiran
 */
public class ViewAllLaptop extends javax.swing.JDialog {

    /**
     * Creates new form ViewAllLaptop
     */
    LaptopManagment lapMgmt;
    DefaultTableModel laptopTbl;
    private PreparedStatement pstat;
    private ResultSet rs;
    private Connection conn;
    //  private SupCtrl supCtr;
    Database db = new Database();

    public ViewAllLaptop(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db.GetDbConnection();
        conn = db.conn;
        showAllLaptop();
        Fillcombobrand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrice1 = new javax.swing.JLabel();
        lblGeneration = new javax.swing.JLabel();
        lbGraphics = new javax.swing.JLabel();
        lblRAM = new javax.swing.JLabel();
        lblHarddisk1 = new javax.swing.JLabel();
        lblProcessor = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtRAM = new javax.swing.JTextField();
        txtGeneration = new javax.swing.JTextField();
        cmbLaptopBrand = new javax.swing.JComboBox();
        txtHarddisk = new javax.swing.JTextField();
        txtGraphics = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        lblHarddisk = new javax.swing.JLabel();
        txtProcessor = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaptops = new javax.swing.JTable();
        txtLapId = new javax.swing.JTextField();
        lblPrice2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnShowAllCustomer = new javax.swing.JButton();
        btnLatestCustomer = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPrice1.setText("laptop id :");

        lblGeneration.setText("Generation :");

        lbGraphics.setText("Graphics :");

        lblRAM.setText("RAM :");

        lblHarddisk1.setText("Model no:");

        lblProcessor.setText("Processor :");

        cmbLaptopBrand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "plz select" }));
        cmbLaptopBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLaptopBrandActionPerformed(evt);
            }
        });

        lblPrice.setText("Price :");

        lblHarddisk.setText("Harddisk :");

        tblLaptops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLaptops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaptopsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLaptops);

        txtLapId.setEditable(false);

        lblPrice2.setText("brandname :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnShowAllCustomer.setText("Show all laptop ");
        btnShowAllCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllCustomerActionPerformed(evt);
            }
        });

        btnLatestCustomer.setText("latest laptop");
        btnLatestCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatestCustomerActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarddisk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarddisk1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarddisk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLaptopBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLapId, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowAllCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnLatestCustomer)
                        .addGap(53, 53, 53)
                        .addComponent(btnDelete)))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLapId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLaptopBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarddisk1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHarddisk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtHarddisk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneration, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProcessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnShowAllCustomer)
                        .addComponent(btnLatestCustomer)
                        .addComponent(btnDelete))
                    .addComponent(btnUpdate))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fillcombobrand() {

        try {
            String sql = "select brandname from tbl_laptopbrand";
            pstat = conn.prepareStatement(sql);
            rs = pstat.executeQuery();

            while (rs.next()) {

                String cusId = rs.getString("brandname");

                cmbLaptopBrand.addItem(cusId);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error = " + e);
        }
    }

    public final void showAllLaptop() {
        lapMgmt = new LaptopManagment();
        laptopTbl = new DefaultTableModel();
        ArrayList<LaptopInfo> laptops = lapMgmt.listAllLaptops();
        String[] columns = {"laptop_id", "model no", "harddisk", "ram", "graphics", "generation", "processor", "price", "brand"};
        laptopTbl.setColumnIdentifiers(columns);
        for (LaptopInfo laptop : laptops) {
            laptopTbl.addRow(new Object[]{laptop.getLaptop_id(), laptop.getModel_no(), laptop.getHarddisk(),
                laptop.getRam(), laptop.getGraphics(), laptop.getGeneration(), laptop.getProcessor(),
                laptop.getPrice(), laptop.getLapBrandInfo().getBrandname()});
        }

        tblLaptops.setModel(laptopTbl);
    }

    public final void showAllLatestLaptop() {
        lapMgmt = new LaptopManagment();
        laptopTbl = new DefaultTableModel();
        ArrayList<LaptopInfo> laptops = lapMgmt.listAllLatestLaptops();
        String[] columns = {"laptop_id", "model no", "harddisk", "ram", "graphics", "generation", "processor", "price", "brand"};
        laptopTbl.setColumnIdentifiers(columns);
        for (LaptopInfo laptop : laptops) {
            laptopTbl.addRow(new Object[]{laptop.getLaptop_id(), laptop.getModel_no(), laptop.getHarddisk(),
                laptop.getRam(), laptop.getGraphics(), laptop.getGeneration(), laptop.getProcessor(),
                laptop.getPrice(), laptop.getLapBrandInfo().getBrandname()});
        }

        tblLaptops.setModel(laptopTbl);
    }


    private void cmbLaptopBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLaptopBrandActionPerformed
        // TODO add your handling code here:
        /* if (cmbLaptopBrand.getSelectedIndex() == 0) {
         JOptionPane.showMessageDialog(null, "select role");
         } else {
         System.out.println("" + cmbLaptopBrand.getSelectedItem());
         }*/
    }//GEN-LAST:event_cmbLaptopBrandActionPerformed

    private void tblLaptopsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaptopsMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblLaptops.getSelectedRow();
            String rowClick = (tblLaptops.getModel().getValueAt(row, 0).toString());
            String sql = "select * from tbl_laptop where laptop_id='" + rowClick + "'";
            pstat = conn.prepareStatement(sql);
            rs = pstat.executeQuery();
            if (rs.next()) {
                String id = rs.getString("laptop_id");
                txtLapId.setText(id);
                String model = rs.getString("model_no");
                txtModel.setText(model);
                String harddisk = rs.getString("harddisk");
                txtHarddisk.setText(harddisk);
                String ram = rs.getString("ram");
                txtRAM.setText(ram);
                String graphics = rs.getString("graphics");
                txtGraphics.setText(graphics);
                String generation = rs.getString("generation");
                txtGeneration.setText(generation);
                String processor = rs.getString("processor");
                txtProcessor.setText(processor);
                String pieces = rs.getString("price");
                txtPrice.setText(pieces);

                cmbLaptopBrand.setSelectedItem(tblLaptops.getModel().getValueAt(row, 8).toString());

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblLaptopsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String model = txtModel.getText();
        String harddisk = txtHarddisk.getText();
        String ram = txtRAM.getText();
        String graphics = txtGraphics.getText();
        String gen = txtGeneration.getText();
        String processor = txtProcessor.getText();
        String price = txtPrice.getText();

        if (!Validate.checkEmpty(model)) {
            if (!Validate.checkEmpty(harddisk)) {
                if (!Validate.checkEmpty(ram)) {
                    if (!Validate.checkEmpty(graphics)) {
                        if (!Validate.checkEmpty(gen)) {
                            if (!Validate.checkEmpty(processor)) {
                                if (!Validate.checkEmpty(price)) {
                                    if (!Validate.checkLengthModel(model)) {
                                        LaptopInfo objLaptopInfo = new LaptopInfo();
                                        LaptopManagment objLaptopManagment = new LaptopManagment();

                                        objLaptopInfo.setLaptop_id(Integer.parseInt(this.txtLapId.getText()));
                                        objLaptopInfo.setModel_no(this.txtModel.getText());
                                        objLaptopInfo.setHarddisk(this.txtHarddisk.getText());
                                        objLaptopInfo.setRam(this.txtRAM.getText());
                                        objLaptopInfo.setGraphics(this.txtGraphics.getText());
                                        objLaptopInfo.setGeneration(this.txtGeneration.getText());
                                        objLaptopInfo.setProcessor(this.txtProcessor.getText());
                                        objLaptopInfo.setPrice(Double.parseDouble(txtPrice.getText()));

                                        String brand = (String) cmbLaptopBrand.getSelectedItem();
                                        LaptopBrandManagement brandCtrl = new LaptopBrandManagement();
                                        LaptopBrandInfo objLaptopBrandInfo = brandCtrl.searchLaptopBrandByName(brand);
                                        objLaptopInfo.setLapBrandInfo(objLaptopBrandInfo);

                                        if (objLaptopManagment.UpdateLaptop(objLaptopInfo) == true) {
                                            JOptionPane.showMessageDialog(null, "Record Updated Sucessfully");
                                            showAllLaptop();
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Error to Update Record");

                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "model should be between 4-20");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "price can not be empty");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "processor can not be empty");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "generation not be empty");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "graphics can not be empty");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ram can not be empty");
                }
            } else {
                JOptionPane.showMessageDialog(null, "hardisk can not be empty");
            }
        } else {
            JOptionPane.showMessageDialog(null, "model can not be empty");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnShowAllCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllCustomerActionPerformed
        // TODO add your handling code here:
        showAllLaptop();
    }//GEN-LAST:event_btnShowAllCustomerActionPerformed

    private void btnLatestCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatestCustomerActionPerformed
        // TODO add your handling code here:
        showAllLatestLaptop();
    }//GEN-LAST:event_btnLatestCustomerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        LaptopInfo objLaptopInfo = new LaptopInfo();
        LaptopManagment objLaptopManagment = new LaptopManagment();

        objLaptopInfo.setLaptop_id(Integer.parseInt(this.txtLapId.getText()));
//        objLaptopInfo.setFirst_name(this.txtFirstName.getText());
//        objLaptopInfo.setMiddle_name(this.txtMiddleName.getText());
//        objLaptopInfo.setLast_name(this.txtLastName.getText());
//        objLaptopInfo.setContact_no(this.txtContactNo.getText());
//        objLaptopInfo.setAddress(this.txtAddress.getText());
//        objLaptopInfo.setEmail(this.txtEmail.getText());

//        String brand = (String) cmbLapModel.getSelectedItem();
//        SupCtrl supCtrl = new SupCtrl();
//        LaptopInfo laptopInfo = supCtrl.findLaptopInfoByModel(brand);
//        objLaptopInfo.setLapInfo(laptopInfo);
        if (objLaptopManagment.deleteLaptop(objLaptopInfo) == true) {
            JOptionPane.showMessageDialog(null, "Delete Record Successfully");
            //reset();
        } else {
            JOptionPane.showMessageDialog(null, "Error to Delete Record");
        }
        showAllLaptop();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLatestCustomer;
    private javax.swing.JButton btnShowAllCustomer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbLaptopBrand;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGraphics;
    private javax.swing.JLabel lblGeneration;
    private javax.swing.JLabel lblHarddisk;
    private javax.swing.JLabel lblHarddisk1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblProcessor;
    private javax.swing.JLabel lblRAM;
    private javax.swing.JTable tblLaptops;
    private javax.swing.JTextField txtGeneration;
    private javax.swing.JTextField txtGraphics;
    private javax.swing.JTextField txtHarddisk;
    private javax.swing.JTextField txtLapId;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProcessor;
    private javax.swing.JTextField txtRAM;
    // End of variables declaration//GEN-END:variables
}
